<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \ClickMeeting\Client();
$client->authenticate('YourAPIKeyHere');

$client->conferences()->add([
    'name' => 'test',
    'room_type' => 'webinar',
    'permanent_room' => 0,
    'access_type' => 3,
    'registration' => [
        'enabled' => true,
    ],
]);

$client->conferences()->edit(321321, [
    'name' => 'test-edit',
]);

$client->conferences()->delete(321321);
